flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: [earth_on_mars_db]

spring:

  datasource:
    url: jdbc:h2:mem:earth_on_mars_db
#    url: jdbc:postgresql://localhost:5432/earth_on_mars_db
    password: postgres
    username: postgres

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true

server:
  port: 8085